config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
    resources :dir_strs do
      resources :file_strs
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dir_strs#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dir_str.rb
class DirStr < ApplicationRecord
  has_many :file_strs, dependent: :destroy
  validates :name, presence: true,
                  length: { minimum: 3 }
  validates :parent_dir, presence: true,  length: { minimum: 3 }
  validates :owner, presence: true, length: { minimum: 3 }

end

app/models/file_str.rb
class FileStr < ApplicationRecord
  belongs_to :dir_str
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dir_strs_controller.rb
class DirStrsController < ApplicationController
  def index
     @dir_strs = DirStr.all
  end

  def show
    @dir_str = DirStr.find(params[:id])
  end

  def new
    @dir_strs = DirStr.new
  end

  def edit
    @dir_strs = DirStr.find(params[:id])
  end

  def create
    #@dir_strs = DirStr.new(params.require(:dir_strs).permit(:name, :parent_dir, :owner))
    @dir_strs = DirStr.new(dir_str_params)
    if @dir_strs.save
      redirect_to @dir_strs
    else
      render 'new'
    end
  end

  def update
    @dir_strs = DirStr.find(params[:id])
    if @dir_strs.update(dir_str_params)
      redirect_to @dir_strs
    else
      render 'edit'
    end
  end


  def destroy
    @dir_strs = DirStr.find(params[:id])
    @dir_strs.destroy

    redirect_to dir_strs_path
  end

  private
  def dir_str_params
    params.require(:dir_str).permit(:name, :parent_dir, :owner)
  end
end

app/controllers/file_strs_controller.rb
class FileStrsController < ApplicationController
  def index
     @file_strs = FileStr.all
  end

  def show
    @file_str = FileStr.find(params[:id])
  end

  def new
    @file_strs = FileStr.new
  end

  def edit
    @file_str = FileStr.find(params[:id])
  end

  def create
    @dir_str = DirStr.find(params[:dir_str_id])
    @file_str = @dir_str.file_strs.create(file_str_params)
    redirect_to dir_str_path(@dir_str)
  end

  def update
    @_strs = FileStr.find(params[:id])
    if @file_strs.update(file_str_params)
      redirect_to @file_strs
    else
      render 'edit'
    end
  end

  def destroy
    @dir_str = DirStr.find(params[:dir_str_id])
    @file_str = @dir_str.file_strs.find(params[:id])
    @file_str.destroy
    redirect_to dir_str_path(@dir_str)
  end


  private
  def file_str_params
    params.require(:file_str).permit(:name, :parent_dir, :owner)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dir_strs_helper.rb
module DirStrsHelper
end

app/helpers/file_strs_helper.rb
module FileStrsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dir_strs/edit.html.erb
<h1>Edit Directory Structur!</h1>
<%= form_with(model: @dir_strs, local: true) do |form| %>

<% if @dir_strs.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@dir_strs.errors.count, "error") %> prohibited
      this Directory from being saved:
    </h2>
    <ul>
      <% @dir_strs.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :parent_dir %><br>
    <%= form.text_field :parent_dir %>
  </p>

  <p>
    <%= form.label :owner %><br>
    <%= form.text_field :owner %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back', dir_strs_path %>

app/views/dir_strs/index.html.erb
<h1>Listing Directory</h1>
<%= link_to 'New Directory', new_dir_str_path %>
<table border="1pt">
  <tr>
    <th>Dir Name</th>
    <th>Parent Dir Name</th>
    <th>Owner Name</th>
    <th></th>
  </tr>

  <% @dir_strs.each do |dir_strs| %>
    <tr>
      <td><%= dir_strs.name%></td>
      <td><%= dir_strs.parent_dir %></td>
      <td><%= dir_strs.owner %></td>
      <td><%= link_to 'Show', dir_str_path(dir_strs) %></td>
      <td><%= link_to 'Edit', edit_dir_str_path(dir_strs) %></td>
      <td><%= link_to 'Destroy', dir_str_path(dir_strs),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New Directory', new_dir_str_path %>
<%= link_to 'Dir Structur', controller: 'dir_strs' %>

app/views/dir_strs/new.html.erb
<h1>Directory Structur!</h1>
<%= form_with scope: :dir_strs, url: dir_strs_path, local: true do |form| %>

<% if @dir_strs.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@dir_strs.errors.count, "error") %> prohibited
      this Directory from being saved:
    </h2>
    <ul>
      <% @dir_strs.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :parent_dir %><br>
    <%= form.text_field :parent_dir %>
  </p>

  <p>
    <%= form.label :owner %><br>
    <%= form.text_field :owner %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back', dir_strs_path %>

app/views/dir_strs/show.html.erb
<p>
  <strong>Dir Name:</strong>
  <%= @dir_str.name %>
</p>

<p>
  <strong>Parent Dir Name:</strong>
  <%= @dir_str.parent_dir %>
</p>

<p>
  <strong>Owner Name:</strong>
  <%= @dir_str.owner %>
</p>


<h2>Files</h2>
<table border="1pt">
  <tr>
    <th>File Name</th>
    <th>Parent Dir Name</th>
    <th>Owner Name</th>
    <th>Dir_id</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Destroy</th>
  </tr>

  <% @dir_str.file_strs.each do |file_str| %>
    <tr>
      <td><%= file_str.name%></td>
      <td><%= file_str.parent_dir %></td>
      <td><%= file_str.owner %></td>
      <td><%= file_str.dir_str_id %></td>
      <td><%= link_to 'Show', dir_str_file_str_path(file_str) %></td>
      <td><%= link_to 'Edit', edit_dir_str_file_str_path(file_str) %></td>
      <td><%= link_to 'Destroy Files', [file_str.dir_str, file_str],
             method: :delete,
             data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>


<h2>Add a File:</h2>
<%= form_with(model: [ @dir_str, @dir_str.file_strs.build ], local: true) do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :parent_dir %><br>
    <%= form.text_field :parent_dir %>
  </p>

  <p>
    <%= form.label :owner %><br>
    <%= form.text_field :owner %>
  </p>

  <p>
    <%= form.label :dir_str_id %><br>
    <%= form.text_field :dir_str_id %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', dir_strs_path %>

app/views/file_strs/edit.html.erb
<h1>Edit File Structur!</h1>
<%= form_with(model: @dir_str_file_str, local: true) do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :parent_dir %><br>
    <%= form.text_field :parent_dir %>
  </p>

  <p>
    <%= form.label :owner %><br>
    <%= form.text_field :owner %>
  </p>

  <p>
    <%= form.label :dir_str_id %><br>
    <%= form.text_field :dir_str_id %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back', dir_str_path %>

app/views/file_strs/index.html.erb
<h1>Listing File</h1>
<%= link_to 'New File', new_file_str_path %>
<table border="1pt">
  <tr>
    <th>File Name</th>
    <th>Parent Dir Name</th>
    <th>Owner Name</th>
    <th></th>
  </tr>

  <% @file_strs.each do |file_strs| %>
    <tr>
      <td><%= file_strs.name%></td>
      <td><%= file_strs.parent_dir %></td>
      <td><%= file_strs.owner %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New Directory', new_file_str_path %>

app/views/file_strs/new.html.erb
<h1>File Structur!</h1>
<%= form_with(model: [ @dir_str, @dir_str.file_str.build ], local: true) do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :parent_dir %><br>
    <%= form.text_field :parent_dir %>
  </p>

  <p>
    <%= form.label :owner %><br>
    <%= form.text_field :owner %>
  </p>

  <p>
    <%= form.label :dir_str_id %><br>
    <%= form.text_field :dir_str_id %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back', dir_str_file_str_path %>

app/views/file_strs/show.html.erb
<p>
  <strong>File Name:</strong>
  <%= @file_str.name %>
</p>

<p>
  <strong>Parent Dir Name:</strong>
  <%= @file_str.parent_dir %>
</p>

<p>
  <strong>Owner Name:</strong>
  <%= @file_str.owner %>
</p>
<%= link_to 'Back', dir_str_path %>

<%= link_to 'Edit', edit_dir_str_file_str_path(@file_str) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DirStrDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello World!</h1>